name: PHP Tests
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development

jobs:
  phpcs_test:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, cs2pr
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup Composer cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
      - name: Check coding standards
        id: phpcs
        run: composer run lint

      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml
        
  phpstan:
    name: PHPStan
    needs: phpcs_test
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: simplexml, mysql
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup Composer cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer
        run: |
          composer install --prefer-dist --no-progress
      - name: PHPStan Static Analysis
        run: composer phpstan